activities:
  spatial.preproc:
    name: segment
    outputs:
      - c1xxx.nii.gz
      - c2xxx.nii.gz
     name: realign
     outputs: 
       - meanxxx (deja cree)
       - rxxx
     name: normalize
     outputs: 
       - wxxx (deja cree)
     name: smooth
       - sxxxx
     name: stat_design
       - SPM.mat
     name: estimate
       - beta_0001.nii
       - beta_0002.nii
       - beta_0003.nii
       - con_0001.nii
       - spmT_0001.nii
       - mask.nii
       - SPM.mat
       - ReMS.nii
       - RPV.nii
  
