import random
import string
import itertools
import json
import argparse

from bids_prov.utils import CONTEXT_URL, get_random_string

def reproducescript_to_commands(lines: list) -> list:
    """ Return a list of commands (one per line) from readlines of a reproducescript """

    commands = []
    for line in lines:
        line = line.lstrip().replace('\n','')

        # Remove blank lines
        if line == '':
            continue
        # Remove comments
        elif line.startswith('%'):
            continue
        # Begining of commands are identified with cfg = [];
        elif line.startswith('cfg = [];'):
            commands.append('')
            commands[-1] += line
            continue
        # Other lines are part of the current command
        else:
            commands[-1] += line

    return commands

def reproducescript_to_bids_prov(filename: str, output_file: str, context_url=CONTEXT_URL, verbose=False,
                     indent=2) -> bool:
    """ Exporter from reproducescript script.m to an output jsonld

    Parameters
    ----------
    filename : str
        input file containing the script generated by reproducescript
    context_url : str, optional
        url of context, by default CONTEXT_URL
    output_file : str, optional
        if None, default is filename with jsonld extension
    indent : int, optional
        2, number of indentation in jsonfile between each object

    Returns
    -------
    bool
        If true, nothing is written in memory because the existing file (if it exists) contains the same content.
    """

    with open(filename, 'r') as file:
        lines = file.readlines()

    files = {}
    activities = {}

    for line in reproducescript_to_commands(lines):

        # Every line is a new activity

        # Give a random Id to the activity
        # add temporary containers for input/output files for the current activity
        current_activity_id = get_random_string()
        current_activity = {
            "Id": current_activity_id,
            "input_files": [],
            "output_files": []
        }

        # Parse command lines
        for sub_command in line.split(';'):

            # List input files
            if sub_command.startswith('cfg.inputfile'):
                input_filename = sub_command.split('=')[1]
                if '{' in input_filename:
                    # Several files
                    input_filenames = input_filename.replace('{','').replace('}','').replace("'",'').replace(" ",'').split(',')
                    for entity in input_filenames:
                        current_activity["input_files"].append({
                                "Id": f"bids::{entity}",
                                "Label": entity
                            })

            # List output files
            if sub_command.startswith('cfg.outputfile'):
                output_filename = sub_command.split('=')[1].replace('{','').replace('}','').replace("'",'').replace(';','').replace(" ",'')
                if output_filename not in files:
                    current_activity["output_files"].append({
                        "Id": f"bids::{output_filename}",
                        "Label": output_filename,
                        "Command": line,
                        "GeneratedBy": [
                            current_activity["Id"]
                        ]
                    })

            # Create new activity
            if sub_command.startswith('ft_'):
                current_activity["Label"] = sub_command.replace('(cfg)', '')
                current_activity["Id"] = f'bids::prov#{current_activity["Label"]}-{current_activity["Id"]}'
                current_activity["Used"] = [f["Id"] for f in current_activity["input_files"]]
                current_activity["AssociatedWith"] = ["bids::prov#fieldtrip-JbWdJR5s"]

            # Curate files
            for file in itertools.chain(current_activity["input_files"], current_activity["output_files"]):
                if file["Id"] not in files:
                    files[file["Id"]] = file

        # Curate activities
        current_activity.pop("input_files")
        current_activity.pop("output_files")
        activities[current_activity_id] = current_activity

    # Replace activity ids
    for file_id, file in files.items():
        new_activity_ids = []
        if "GeneratedBy" in file:
            for activity in file["GeneratedBy"]:
                if activity in activities:
                    new_activity_ids.append(activities[activity]["Id"])
            file["GeneratedBy"] = new_activity_ids

    # Write output JSON-LD file
    with open(output_file, 'w', encoding = 'utf-8') as file:
        file.write(
            json.dumps(
                {
                    "@context": context_url,
                    "Records": {
                        "Activities": list(activities.values()),
                        "Files": list(files.values())
                    }
                },
                indent=indent)
        )

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--input_file", type=str, required=True,
                        help="input script.m generated by reproducescript")
    parser.add_argument("--output_file", type=str, required=True,
                        help="output provenance JSON-LD file")
    parser.add_argument("--context_url", default=CONTEXT_URL, help="CONTEXT_URL")
    opt = parser.parse_args()

    reproducescript_to_bids_prov(opt.input_file, context_url=opt.context_url, output_file=opt.output_file)
